In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib as plt
from itertools import chain
import ast
from formatAndSplit import get_data, prep_data, undersample, findBestWeight


In [2]:
%%time

from formatAndSplit import get_data, prep_data, undersample, findBestWeight

df = get_data()
X_train, X_dev, X_test, y_train, y_dev, y_test = prep_data(df, "CHM2210", 10)
print(findBestWeight(X_train, y_train, 0.01))

(9424, 464) (1178, 464) (1179, 464)
Weight: 0.01, F1 for class 0: 0.0178
Weight: 0.02, F1 for class 0: 0.0026
Weight: 0.03, F1 for class 0: 0.0153
Weight: 0.04, F1 for class 0: 0.0026
Weight: 0.05, F1 for class 0: 0.0077
Weight: 0.06, F1 for class 0: 0.0077
Weight: 0.07, F1 for class 0: 0.0178
Weight: 0.08, F1 for class 0: 0.0052
Weight: 0.09, F1 for class 0: 0.0051
Weight: 0.10, F1 for class 0: 0.0077
Weight: 0.11, F1 for class 0: 0.0052
Weight: 0.12, F1 for class 0: 0.0153
Weight: 0.13, F1 for class 0: 0.0153
Weight: 0.14, F1 for class 0: 0.0153
Weight: 0.15, F1 for class 0: 0.0278
Weight: 0.16, F1 for class 0: 0.0277
Weight: 0.17, F1 for class 0: 0.0302
Weight: 0.18, F1 for class 0: 0.0400
Weight: 0.19, F1 for class 0: 0.0326
Weight: 0.20, F1 for class 0: 0.0301
Weight: 0.21, F1 for class 0: 0.0277
Weight: 0.22, F1 for class 0: 0.0253
Weight: 0.23, F1 for class 0: 0.0376
Weight: 0.24, F1 for class 0: 0.0252
Weight: 0.25, F1 for class 0: 0.0304
Weight: 0.26, F1 for class 0: 0.0203
We

In [3]:
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
# def xgboostClassifier(X_train, X_dev, X_test, y_train, y_dev, y_test):

#     minWeight = findBestWeight(X_train, y_train, X_dev, y_dev)
#     X_resampled, y_resampled = undersample(X_train, y_train, minWeight)
    
#     xgb_classifier = XGBClassifier(
#         objective='binary:logistic',
#         seed=50,
#         learning_rate=0.01,
#         max_depth=9,
#         n_estimators=100,
#         subsample=0.8,
#         colsample_bytree=0.8
#     )
#     xgb_classifier.fit(X_resampled, y_resampled)
    
#     # Make predictions on the test set
#     y_pred = xgb_classifier.predict(X_test)
    
#     # Evaluate the model performance
#     accuracy = accuracy_score(y_test, y_pred)
#     print(f"Accuracy: {accuracy:.2f}")
    
#     # Confusion matrix and classification report
#     conf_matrix = confusion_matrix(y_test, y_pred)
#     print(f"Confusion Matrix:\n{conf_matrix}")
    
#     class_report = classification_report(y_test, y_pred)
#     print(f"Classification Report:\n{class_report}")

def xgboostClassifier(X_train, X_test, y_train, y_test):
    xgb_classifier = XGBClassifier(
        objective='binary:logistic',
        seed=50,
        learning_rate=0.01,
        max_depth=9,
        n_estimators=100,
        subsample=0.8,
        colsample_bytree=0.8
    )
    xgb_classifier.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred = xgb_classifier.predict(X_test)
    
    # Evaluate the model performance
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {accuracy:.2f}")
    
    # Confusion matrix and classification report
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix:\n{conf_matrix}")
    
    class_report = classification_report(y_test, y_pred)
    print(f"Classification Report:\n{class_report}")
    
    # print(best_model.predict_proba(X_dev))

In [4]:
%%time

from xgboost import XGBClassifier
from sklearn.metrics import f1_score, classification_report, confusion_matrix, accuracy_score

test_classes = ["CHM2210", "STA2023", "MAC1147", "PSY2012", "BSC2010", "ECO2013", "ACG2021", "MAC2311", "ACG3103"]

for tc in test_classes:
    print(tc)
    X_train, X_dev, X_test, y_train, y_dev, y_test = prep_data(df, tc, 10)
    best_weight = findBestWeight(X_train, y_train, 0.01)
    X_resampled, y_resampled = undersample(X_train, y_train, best_weight)
    xgboostClassifier(X_resampled, X_dev, y_resampled, y_dev)
    print("Best Weight:", best_weight)
    print("\n\n\n")
    



CHM2210
(9424, 464) (1178, 464) (1179, 464)
Weight: 0.01, F1 for class 0: 0.0178
Weight: 0.02, F1 for class 0: 0.0026
Weight: 0.03, F1 for class 0: 0.0153
Weight: 0.04, F1 for class 0: 0.0026
Weight: 0.05, F1 for class 0: 0.0077
Weight: 0.06, F1 for class 0: 0.0077
Weight: 0.07, F1 for class 0: 0.0178
Weight: 0.08, F1 for class 0: 0.0052
Weight: 0.09, F1 for class 0: 0.0051
Weight: 0.10, F1 for class 0: 0.0077
Weight: 0.11, F1 for class 0: 0.0052
Weight: 0.12, F1 for class 0: 0.0153
Weight: 0.13, F1 for class 0: 0.0153
Weight: 0.14, F1 for class 0: 0.0153
Weight: 0.15, F1 for class 0: 0.0278
Weight: 0.16, F1 for class 0: 0.0277
Weight: 0.17, F1 for class 0: 0.0302
Weight: 0.18, F1 for class 0: 0.0400
Weight: 0.19, F1 for class 0: 0.0326
Weight: 0.20, F1 for class 0: 0.0301
Weight: 0.21, F1 for class 0: 0.0277
Weight: 0.22, F1 for class 0: 0.0253
Weight: 0.23, F1 for class 0: 0.0376
Weight: 0.24, F1 for class 0: 0.0252
Weight: 0.25, F1 for class 0: 0.0304
Weight: 0.26, F1 for class 0: 0

In [5]:
%%time

# from sklearn.model_selection import GridSearchCV
# import xgboost as xgb
# def xgboostClassifier(X_train, X_dev, X_test, y_train, y_dev, y_test):

#     # minWeight = optimize_f1_for_class_0(X_train, y_train, X_dev, y_dev)
#     X_resampled, y_resampled = undersample(X_train, y_train, 1)
    
#     xgb_classifier = XGBClassifier(
#         objective='binary:logistic',
#         seed=50,
#         learning_rate=0.01,
#         max_depth=9,
#         n_estimators=100,
#         subsample=0.8,
#         colsample_bytree=0.8
#     )
#     xgb_classifier.fit(X_resampled, y_resampled)
    
#     # Make predictions on the test set
#     y_pred = xgb_classifier.predict(X_test)
    
#     # Evaluate the model performance
#     accuracy = accuracy_score(y_test, y_pred)
#     print(f"Accuracy: {accuracy:.2f}")
    
#     # Confusion matrix and classification report
#     conf_matrix = confusion_matrix(y_test, y_pred)
#     print(f"Confusion Matrix:\n{conf_matrix}")
    
#     class_report = classification_report(y_test, y_pred)
#     print(f"Classification Report:\n{class_report}")
    
#     # print(best_model.predict_proba(X_dev))

# from xgboost import XGBClassifier
# from sklearn.metrics import f1_score, classification_report, confusion_matrix, accuracy_score

test_classes = ["CHM2210", "STA2023", "MAC1147", "PSY2012", "BSC2010", "ECO2013", "ACG2021", "MAC2311", "ACG3103"]

for tc in test_classes:
    print(tc)
    X_train, X_dev, X_test, y_train, y_dev, y_test = prep_data(df, tc, 10)
    X_resampled, y_resampled = undersample(X_train, y_train)
    xgboostClassifier(X_resampled, X_dev, y_resampled, y_dev)
    print("Best Weight:", best_weight)
    print("\n\n\n")
    



CHM2210
(9424, 464) (1178, 464) (1179, 464)
Accuracy: 0.72
Confusion Matrix:
[[118  34]
 [301 725]]
Classification Report:
              precision    recall  f1-score   support

           0       0.28      0.78      0.41       152
           1       0.96      0.71      0.81      1026

    accuracy                           0.72      1178
   macro avg       0.62      0.74      0.61      1178
weighted avg       0.87      0.72      0.76      1178

Best Weight: 1.0




STA2023
(13444, 632) (1680, 632) (1681, 632)
Accuracy: 0.69
Confusion Matrix:
[[ 150   32]
 [ 491 1007]]
Classification Report:
              precision    recall  f1-score   support

           0       0.23      0.82      0.36       182
           1       0.97      0.67      0.79      1498

    accuracy                           0.69      1680
   macro avg       0.60      0.75      0.58      1680
weighted avg       0.89      0.69      0.75      1680

Best Weight: 1.0




MAC1147
(7092, 336) (886, 336) (887, 336)
Accuracy: 0

In [6]:
%%time

from xgboost import XGBClassifier
from sklearn.metrics import f1_score, classification_report, confusion_matrix, accuracy_score

test_classes = ["CHM2210", "STA2023", "MAC1147", "PSY2012", "BSC2010", "ECO2013", "ACG2021", "MAC2311", "ACG3103"]

for tc in test_classes:
    print(tc)
    X_train, X_dev, X_test, y_train, y_dev, y_test = prep_data(df, tc, 10)
    best_weight = findBestWeight(X_train, y_train, 0.02)
    X_resampled, y_resampled = undersample(X_train, y_train, best_weight)
    xgboostClassifier(X_resampled, X_dev, y_resampled, y_dev)
    print("Best Weight:", best_weight)
    print("\n\n\n")
    



CHM2210
(9424, 464) (1178, 464) (1179, 464)
Weight: 0.02, F1 for class 0: 0.0026
Weight: 0.04, F1 for class 0: 0.0026
Weight: 0.06, F1 for class 0: 0.0077
Weight: 0.08, F1 for class 0: 0.0052
Weight: 0.10, F1 for class 0: 0.0077
Weight: 0.12, F1 for class 0: 0.0153
Weight: 0.14, F1 for class 0: 0.0153
Weight: 0.16, F1 for class 0: 0.0277
Weight: 0.18, F1 for class 0: 0.0400
Weight: 0.20, F1 for class 0: 0.0301
Weight: 0.22, F1 for class 0: 0.0253
Weight: 0.24, F1 for class 0: 0.0252
Weight: 0.26, F1 for class 0: 0.0203
Weight: 0.28, F1 for class 0: 0.0326
Weight: 0.30, F1 for class 0: 0.0425
Weight: 0.32, F1 for class 0: 0.0402
Weight: 0.34, F1 for class 0: 0.0689
Weight: 0.36, F1 for class 0: 0.0472
Weight: 0.38, F1 for class 0: 0.0682
Weight: 0.40, F1 for class 0: 0.1091
Weight: 0.42, F1 for class 0: 0.1133
Weight: 0.44, F1 for class 0: 0.1108
Weight: 0.46, F1 for class 0: 0.1107
Weight: 0.48, F1 for class 0: 0.1341
Weight: 0.50, F1 for class 0: 0.1336
Weight: 0.52, F1 for class 0: 0

In [7]:
%%time

from xgboost import XGBClassifier
from sklearn.metrics import f1_score, classification_report, confusion_matrix, accuracy_score

test_classes = ["CHM2210", "STA2023", "MAC1147", "PSY2012", "BSC2010", "ECO2013", "ACG2021", "MAC2311", "ACG3103"]

for tc in test_classes:
    print(tc)
    X_train, X_dev, X_test, y_train, y_dev, y_test = prep_data(df, tc, 10)
    best_weight = findBestWeight(X_train, y_train, 0.05)
    X_resampled, y_resampled = undersample(X_train, y_train, best_weight)
    xgboostClassifier(X_resampled, X_dev, y_resampled, y_dev)
    print("Best Weight:", best_weight)
    print("\n\n\n")
    



CHM2210
(9424, 464) (1178, 464) (1179, 464)
Weight: 0.05, F1 for class 0: 0.0077
Weight: 0.10, F1 for class 0: 0.0077
Weight: 0.15, F1 for class 0: 0.0278
Weight: 0.20, F1 for class 0: 0.0301
Weight: 0.25, F1 for class 0: 0.0304
Weight: 0.30, F1 for class 0: 0.0425
Weight: 0.35, F1 for class 0: 0.0494
Weight: 0.40, F1 for class 0: 0.1091
Weight: 0.45, F1 for class 0: 0.1063
Weight: 0.50, F1 for class 0: 0.1336
Weight: 0.55, F1 for class 0: 0.1633
Weight: 0.60, F1 for class 0: 0.1764
Weight: 0.65, F1 for class 0: 0.2337
Weight: 0.70, F1 for class 0: 0.2878
Weight: 0.75, F1 for class 0: 0.3605
Weight: 0.80, F1 for class 0: 0.4003
Weight: 0.85, F1 for class 0: 0.4209
Weight: 0.90, F1 for class 0: 0.4395
Weight: 0.95, F1 for class 0: 0.4361
Weight: 1.00, F1 for class 0: 0.3839
Accuracy: 0.80
Confusion Matrix:
[[ 86  66]
 [173 853]]
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.57      0.42       152
           1       0.93     

In [8]:
# %%time

# from xgboost import XGBClassifier
# from sklearn.metrics import f1_score, classification_report, confusion_matrix, accuracy_score

# test_classes = ["CHM2210", "STA2023", "MAC1147", "PSY2012", "BSC2010", "ECO2013", "ACG2021", "MAC2311", "ACG3103"]

# for tc in test_classes:
#     print(tc)
#     X_train, X_dev, X_test, y_train, y_dev, y_test = prep_data(df, tc, 10)
#     best_weight = findBestWeight(X_train, y_train, 0.001)
#     X_resampled, y_resampled = undersample(X_train, y_train, best_weight)
#     xgboostClassifier(X_resampled, X_dev, y_resampled, y_dev)
#     print("Best Weight:", best_weight)
#     print("\n\n\n")
    

